# Generated by Django 3.0 on 2019-12-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fallas_detectadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='hora_termino',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='id_ascensor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='modelo_ascensor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='piezas_cambiadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='reparacion_efectuada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
