# Generated by Django 3.0 on 2019-12-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191216_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
